name: Azure Web Calling CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    # Build and Test Server
    - name: Install Server dependencies
      working-directory: ./Server
      run: npm ci

    - name: Build Server
      working-directory: ./Server
      run: npm run build

    - name: Test Server
      working-directory: ./Server
      run: npm test

    # Build Client
    - name: Install Calling dependencies
      working-directory: ./Calling
      run: npm ci

    - name: Build Calling App
      working-directory: ./Calling
      run: npm run build
